<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
		<PackageReference Include="Microsoft.Data.SqlClient.SNI.runtime" Version="5.2.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Microsoft.Office.Interop.Excel">
			<!-- Office 2016 için 64-bit veya 32-bit kurulu olan doğru yolu girin -->
			<HintPath>C:\Program Files\Microsoft Office\root\Office16\Microsoft.Office.Interop.Excel.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

</Project>